# SPDX-License-Identifier: GPL-2.0

ifeq ($(CONFIG_SPL_BUILD),)

ifeq ($(CONFIG_FAILSAFE_LEGACY_UI),y)
obj-y += fsdata-legacy/
else
obj-y += fsdata/
endif

obj-y += fs.o failsafe.o failsafe_sysbackup.o

endif
